apiVersion: v1
kind: Service
metadata:
  name: spin-clouddriver-ro
  namespace: spinnaker
  labels:
    app: spin
    stack: clouddriver
    detail: ro
spec:
  ports:
    - port: 7002
  selector:
    load-balancer-spin-clouddriver-ro: "true"
