apiVersion: v1
kind: Service
metadata:
  name: data-redis-server
  namespace: spinnaker
  labels:
    app: data
    stack: redis
    detail: server
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    load-balancer-data-redis-server: "true"
