apiVersion: v1
kind: Service
metadata:
  name: spin-deck
  namespace: spinnaker
  labels:
    app: spin
    stack: deck
spec:
  ports:
    - port: 9000
  selector:
    load-balancer-spin-deck: "true"
