apiVersion: v1
kind: ReplicationController
metadata:
  name: spin-echo-event-v000
  namespace: spinnaker
  labels:
    app: spin
    stack: echo
    detail: event
    version: v000
spec:
  replicas: 1
  selector:
    replication-controller: spin-echo-event-v000
  template:
    metadata:
      labels:
        replication-controller: spin-echo-event-v000
        load-balancer-spin-echo-event: "true"
    spec:
      containers:
        - image: quay.io/spinnaker/echo:master
          name: echo
          ports:
            - containerPort: 8089
              name: echo
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: echo-event-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8089
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
        - name: echo-event-config
          secret:
            secretName: echo-event-config
