apiVersion: v1
kind: Service
metadata:
  name: redis-igor-master
  namespace: spinnaker
  labels:
    app: redis
    stack: igor
    detail: master
spec:
  ports:
    - port: 6379
  selector:
    load-balancer-redis-igor-master: "true"
