apiVersion: v1
kind: Service
metadata:
  name: redis-rosco-master
  namespace: spinnaker
  labels:
    app: redis
    stack: rosco
    detail: master
spec:
  ports:
    - port: 6379
  selector:
    load-balancer-redis-rosco-master: "true"
