apiVersion: v1
kind: Service
metadata:
  name: redis-orca-master
  namespace: spinnaker
  labels:
    app: redis
    stack: orca
    detail: master
spec:
  ports:
    - port: 6379
  selector:
    load-balancer-redis-orca-master: "true"
