apiVersion: v1
kind: Service
metadata:
  name: spin-gate
  namespace: spinnaker
  labels:
    app: spin
    stack: gate
spec:
  ports:
    - port: 8084
  selector:
    load-balancer-spin-gate: "true"
