apiVersion: v1
kind: Service
metadata:
  name: spin-fiat-ro
  namespace: spinnaker
  labels:
    app: spin
    stack: fiat
    detail: ro
spec:
  ports:
    - port: 7003
  selector:
    load-balancer-spin-fiat-ro: "true"
