server:
  port: ${services.igor.port:8088}
  address: ${services.igor.host:localhost}

jenkins:
  enabled: true
  masters:
    # - name: jenkins-local
    #   address: "http://192.168.99.1:8888"
    #   username: jenkins
    #   password: jenkins
    - name: jenkins-test
      address: "http://10.213.131.18:8080/jenkins"
      username: jenkins
      password: jenkins
    # - name: jenkins-prod
    #   address: "http://10.213.58.205:8080/jenkins"
    #   username: jenkins
    #   password: jenkins

travis:
  enabled: ${services.travis.enabled:false}
  masters:
    - name: ${services.travis.defaultMaster.name}
      baseUrl: ${services.travis.defaultMaster.baseUrl}
      address: ${services.travis.defaultMaster.address}
      githubToken: ${services.travis.defaultMaster.githubToken}

dockerRegistry:
  enabled: true

redis:
  # connection: redis://192.168.99.1:6379
  connection: redis://10.213.130.41:10841

# Igor depends on Clouddriver and Echo. These are normally configured
# in spinnaker[-local].yml (if present), otherwise, uncomment this.
# services:
#   clouddriver:
#     baseUrl: ${services.clouddriver.baseUrl}
#   echo:
#     baseUrl: ${services.echo.baseUrl}

spectator:
  applicationName: ${spring.application.name}
  webEndpoint:
    enabled: ${services.spectator.webEndpoint.enabled:false}
    prototypeFilter:
      path: ${services.spectator.webEndpoint.prototypeFilter.path:}

  stackdriver:
    enabled: ${services.stackdriver.enabled}
    projectName: ${services.stackdriver.projectName}
    credentialsPath: ${services.stackdriver.credentialsPath}
