apiVersion: v1
kind: Service
metadata:
  name: spin-front50
  namespace: spinnaker
  labels:
    app: spin
    stack: front50
spec:
  ports:
    - port: 8080
  selector:
    load-balancer-spin-front50: "true"
