apiVersion: v1
kind: ReplicationController
metadata:
  name: spin-front50-v000
  namespace: spinnaker
  labels:
    app: spin
    stack: front50
    version: v000
spec:
  replicas: 1
  selector:
    replication-controller: spin-front50-v000
  template:
    metadata:
      labels:
        replication-controller: spin-front50-v000
        load-balancer-spin-front50: "true"
    spec:
      containers:
        - image: quay.io/spinnaker/front50:master
          name: front50
          ports:
            - containerPort: 8080
              name: front50
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: front50-config
            - mountPath: /root/.gcp/
              name: gcp-config
            - mountPath: /root/.aws/
              name: aws-config
          readinessProbe:
            httpGet:
              path: /info # This should be /health, see https://github.com/spinnaker/spinnaker/issues/1018
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
        - name: front50-config
          secret:
            secretName: front50-config
        - name: gcp-config
          secret:
            secretName: gcp-config
        - name: aws-config
          secret:
            secretName: aws-config
