server:
  port: ${services.echo.port:8089}
  address: ${services.echo.address}

cassandra:
  enabled: false
  embedded: false

spinnaker:
  baseUrl: ${services.deck.baseUrl}
  cassandra:
   enabled: false
  inMemory:
   enabled: true

front50:
  baseUrl: ${services.front50.baseUrl:http://localhost:8080}

orca:
  baseUrl: ${services.orca.baseUrl:http://localhost:8083}

endpoints.health.sensitive: false

slack:
  enabled: ${services.echo.notifications.slack.enabled:false}
  token: ${services.echo.notifications.slack.token}

spring:
  mail:
    host: ${mail.host}

mail:
  enabled: ${services.echo.notifications.mail.enabled:false}
  host: ${services.echo.notifications.mail.host}
  from: ${services.echo.notifications.mail.fromAddress}

hipchat:
  enabled: ${services.echo.notifications.hipchat.enabled:false}
  baseUrl: ${services.echo.notifications.hipchat.url}
  token: ${services.echo.notifications.hipchat.token}

twilio:
  enabled: ${services.echo.notifications.sms.enabled:false}
  baseUrl: ${services.echo.notifications.sms.url:https://api.twilio.com/}
  account: ${services.echo.notifications.sms.account}
  token: ${services.echo.notifications.sms.token}
  from: ${services.echo.notifications.sms.from}
