apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: data-redis-sentinel-v000
  namespace: spinnaker
  labels:
    app: data
    stack: redis
    details: sentinel
    version: v000
spec:
  replicas: 1
  selector:
    matchLabels:
      replication-controller-prime: data-redis-sentinel-v000
  template:
    metadata:
      labels:
        replication-controller: data-redis-sentinel-v000
        replication-controller-prime: data-redis-sentinel-v000
        load-balancer-data-redis-sentinel: "true"
    spec:
      containers:
      - name: redis-sentinel
        image: gcr.io/kubernetes-spinnaker/redis-cluster:v2
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379
