apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: data-redis-master-v000
  namespace: spinnaker
  labels:
    app: data
    stack: redis
    details: master
    version: v000
spec:
  replicas: 1
  selector:
    matchLabels:
      replication-controller: data-redis-master-v000
  template:
    metadata:
      labels:
        replication-controller: data-redis-master-v000
        load-balancer-data-redis-server: "true"
    spec:
      containers:
        - name: redis-master
          image: gcr.io/kubernetes-spinnaker/redis-cluster:v2
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "0.1"
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
      volumes:
        - name: data
          emptyDir: {}
