apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: data-redis-server-v000
  namespace: spinnaker
  labels:
    app: data
    stack: redis
    details: server
    version: v000
spec:
  replicas: 1
  selector:
    matchLabels:
      replication-controller: data-redis-server-v000
  template:
    metadata:
      labels:
        replication-controller: data-redis-server-v000
        load-balancer-data-redis-server: "true"
    spec:
      containers:
      - name: redis-server
        image: gcr.io/kubernetes-spinnaker/redis-cluster:v2
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data
          emptyDir: {}
