apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: spin-igor-v000
  namespace: spinnaker
  labels:
    app: spin
    stack: igor
    version: v000
spec:
  replicas: 1
  selector:
    matchLabels:
      replication-controller: spin-igor-v000
  template:
    metadata:
      labels:
        replication-controller: spin-igor-v000
        load-balancer-spin-igor: "true"
    spec:
      containers:
        - image: quay.io/spinnaker/igor:master
          imagePullPolicy: Always
          name: igor
          ports:
            - containerPort: 8088
              name: igor
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: spinnaker-config
          readinessProbe:
            httpGet:
              path: /env
              port: 8088
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
        - name: spinnaker-config
          secret:
            secretName: spinnaker-config
