apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: spin-echo-v000
  namespace: spinnaker
  labels:
    app: spin
    stack: echo
    version: v000
spec:
  replicas: 1
  selector:
    matchLabels:
      replication-controller: spin-echo-v000
  template:
    metadata:
      labels:
        replication-controller: spin-echo-v000
        load-balancer-spin-echo: "true"
    spec:
      containers:
        - image: quay.io/spinnaker/echo:master
          imagePullPolicy: Always
          name: echo
          ports:
            - containerPort: 8089
              name: echo
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: spinnaker-config
          readinessProbe:
            httpGet:
              path: /env
              port: 8089
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
        - name: spinnaker-config
          secret:
            secretName: spinnaker-config
