server:
  port: ${services.orca.port:8083}
  address: ${services.orca.address}

oort:
  baseUrl: ${services.clouddriver.mutate.baseUrl}

mort:
  baseUrl: ${services.clouddriver.mutate.baseUrl}

kato:
  baseUrl: ${services.clouddriver.mutate.baseUrl}

front50:
  baseUrl: ${services.front50.baseUrl}

bakery:
  baseUrl: ${services.bakery.baseUrl}
  extractBuildDetails: ${services.bakery.extractBuildDetails:true}
  allowMissingPackageInstallation: ${services.bakery.allowMissingPackageInstallation:false}

echo:
  enabled: ${services.echo.enabled:false}
  baseUrl: ${services.echo.event.baseUrl:8089}

igor:
  baseUrl: ${services.igor.baseUrl:8088}

# TODO(duftler): Remove this once flex is conditionally-enabled in orca.
flex:
  baseUrl: http://not-a-host

default:
  bake:
    account: 
  securityGroups:
  vpc:
    securityGroups:

redis:
  connection: ${services.redis.orca.master.connection}

tasks:
  executionWindow:
    timezone: ${services.orca.timezone}
