apiVersion: v1
kind: Service
metadata:
  name: spin-echo-event
  namespace: spinnaker
  labels:
    app: spin
    stack: echo
    detail: event
spec:
  ports:
    - port: 8089
  selector:
    load-balancer-spin-echo-event: "true"
