apiVersion: v1
kind: ReplicationController
metadata:
  name: spin-clouddriver-mutate-v000
  namespace: spinnaker
  labels:
    app: spin
    stack: clouddriver
    detail: mutate
    version: v000
spec:
  replicas: 3
  selector:
    replication-controller: spin-clouddriver-mutate-v000
  template:
    metadata:
      labels:
        replication-controller: spin-clouddriver-mutate-v000
        load-balancer-spin-clouddriver-mutate: "true"
    spec:
      containers:
        - image: quay.io/spinnaker/clouddriver:master
          name: clouddriver
          ports:
            - containerPort: 7002
              name: clouddriver
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: clouddriver-mutate-config
            - mountPath: /root/.kube
              name: kube-config
            - mountPath: /root/.gcp
              name: gcp-config
          readinessProbe:
            httpGet:
              path: /credentials
              port: 7002
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
        - name: clouddriver-mutate-config
          secret:
            secretName: clouddriver-mutate-config
        - name: kube-config
          secret:
            secretName: kube-config
        - name: gcp-config
          secret:
            secretName: gcp-config
